#!/usr/bin/env bash
# generate-config.sh
# Reads credentials from a Frappe bench and generates frappe_lightning/config.yaml.
#
# Usage:
#   ./scripts/generate-config.sh --bench /home/frappe/frappe-bench --site erp.local
#   ./scripts/generate-config.sh --bench /home/frappe/frappe-bench --site erp.local \
#       --lightning-pass mysecret --meili-key mykey --api-token mytoken
#
# Requirements: python3 (available in any Frappe bench environment)

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────────────────────
BENCH_PATH=""
SITE_NAME=""
LIGHTNING_USER="lightning"
LIGHTNING_PASS=""
MEILI_HOST="http://localhost:7700"
MEILI_KEY=""
MARIADB_HOST="127.0.0.1"
MARIADB_PORT="3306"
SERVER_ID="100"
API_PORT="8765"
AI_MODE="off"
API_TOKEN=""
OUTPUT="frappe_lightning/config.yaml"

# ── Argument parsing ───────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case $1 in
    --bench)           BENCH_PATH="$2";      shift 2 ;;
    --site)            SITE_NAME="$2";       shift 2 ;;
    --lightning-user)  LIGHTNING_USER="$2";  shift 2 ;;
    --lightning-pass)  LIGHTNING_PASS="$2";  shift 2 ;;
    --meili-host)      MEILI_HOST="$2";      shift 2 ;;
    --meili-key)       MEILI_KEY="$2";       shift 2 ;;
    --mariadb-host)    MARIADB_HOST="$2";    shift 2 ;;
    --mariadb-port)    MARIADB_PORT="$2";    shift 2 ;;
    --server-id)       SERVER_ID="$2";       shift 2 ;;
    --api-port)        API_PORT="$2";        shift 2 ;;
    --ai-mode)         AI_MODE="$2";         shift 2 ;;
    --api-token)       API_TOKEN="$2";       shift 2 ;;
    --output)          OUTPUT="$2";          shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Validate required args ─────────────────────────────────────────────────────
if [[ -z "$BENCH_PATH" ]]; then
  read -rp "Frappe bench path (e.g. /home/frappe/frappe-bench): " BENCH_PATH
fi
if [[ -z "$SITE_NAME" ]]; then
  # List available sites
  echo "Available sites:"
  ls "${BENCH_PATH}/sites/" | grep -v -E '^(apps|assets|common)' || true
  read -rp "Site name (e.g. erp.local): " SITE_NAME
fi

SITE_CONFIG="${BENCH_PATH}/sites/${SITE_NAME}/site_config.json"
COMMON_CONFIG="${BENCH_PATH}/sites/common_site_config.json"

if [[ ! -f "$SITE_CONFIG" ]]; then
  echo "ERROR: site_config.json not found at $SITE_CONFIG"
  exit 1
fi

echo ""
echo "==> Reading bench credentials from:"
echo "    $SITE_CONFIG"
echo "    $COMMON_CONFIG"

# ── Extract values with python3 (always available in bench env) ───────────────
py3() { python3 -c "$1"; }

DB_NAME=$(py3 "import json; d=json.load(open('${SITE_CONFIG}')); print(d.get('db_name',''))")

# Redis: parse "redis://host:port" from common config
REDIS_CACHE_URL=$(py3 "
import json, sys
try:
    d = json.load(open('${COMMON_CONFIG}'))
    print(d.get('redis_cache', 'redis://127.0.0.1:11000'))
except:
    print('redis://127.0.0.1:11000')
")
REDIS_HOST=$(py3 "u='${REDIS_CACHE_URL}'; parts=u.replace('redis://','').split(':'); print(parts[0])")
REDIS_PORT=$(py3 "u='${REDIS_CACHE_URL}'; parts=u.replace('redis://','').split(':'); print(parts[1] if len(parts)>1 else '11000')")

# Frappe's site URL (used for CORS)
FRAPPE_URL="http://localhost:8000"
WEB_PORT=$(py3 "
import json, sys
try:
    d = json.load(open('${COMMON_CONFIG}'))
    print(d.get('webserver_port', 8000))
except:
    print(8000)
")
FRAPPE_URL="http://localhost:${WEB_PORT}"

echo "    db_name:     ${DB_NAME}"
echo "    redis_cache: ${REDIS_HOST}:${REDIS_PORT}"
echo "    site_url:    ${FRAPPE_URL}"

# ── Interactive prompts for secrets not yet provided ──────────────────────────
if [[ -z "$LIGHTNING_PASS" ]]; then
  read -rsp "Lightning DB user password (from setup-mariadb.sh): " LIGHTNING_PASS
  echo
fi

if [[ -z "$MEILI_KEY" ]]; then
  MEILI_KEY=$(openssl rand -hex 24)
  echo "Generated Meilisearch master key: ${MEILI_KEY}"
  echo "  (use this key when starting Meilisearch)"
fi

if [[ -z "$API_TOKEN" ]]; then
  API_TOKEN=$(openssl rand -hex 32)
  echo "Generated Lightning API token:    ${API_TOKEN}"
fi

# ── Write config.yaml ─────────────────────────────────────────────────────────
mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" <<EOF
# Generated by generate-config.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Bench: ${BENCH_PATH}  Site: ${SITE_NAME}

sites:
  - name: ${SITE_NAME}
    mariadb:
      host: ${MARIADB_HOST}
      port: ${MARIADB_PORT}
      user: ${LIGHTNING_USER}
      password: ${LIGHTNING_PASS}
      server_id: ${SERVER_ID}
    meilisearch:
      host: ${MEILI_HOST}
      master_key: ${MEILI_KEY}
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    api:
      port: ${API_PORT}
      allowed_origins: "${FRAPPE_URL}"
    doctypes:
      - name: Sales Invoice
        table: "tabSales Invoice"
      - name: Customer
        table: tabCustomer
      - name: Item
        table: tabItem
      - name: Purchase Order
        table: "tabPurchase Order"
      - name: Supplier
        table: tabSupplier
      - name: Lead
        table: tabLead

# AI mode: off | local | cloud
ai_mode: ${AI_MODE}
embedding_server_url: "http://localhost:5000/embed"
vector_dimensions: 384

# Bearer token for external API access — keep this secret
api_token: "${API_TOKEN}"
EOF

echo ""
echo "==> Config written to: ${OUTPUT}"
echo ""
echo "Summary:"
echo "  Site:          ${SITE_NAME}"
echo "  MariaDB:       ${MARIADB_HOST}:${MARIADB_PORT}  user=${LIGHTNING_USER}"
echo "  Meilisearch:   ${MEILI_HOST}  key=${MEILI_KEY}"
echo "  Redis:         ${REDIS_HOST}:${REDIS_PORT}"
echo "  API port:      ${API_PORT}"
echo "  API token:     ${API_TOKEN}"
echo ""
echo "Next steps:"
echo "  1. Start Meilisearch with --master-key='${MEILI_KEY}'"
echo "  2. Build Lightning:  cd frappe_lightning && go build -o ../lightning-server ./main.go"
echo "  3. Start server:     ./lightning-server --config ${OUTPUT}"
echo "  4. Run backfill:     ./scripts/backfill-all.sh --config ${OUTPUT} --site ${SITE_NAME}"
